### ISSUE TITLE
Project owner能不能加一点简单的自身情况的介绍

### ISSUE THREAD

**Issue by caiwan-msft** [LennyNiu/HowToRaiseChild#4]
Hi Lenny, 

很高兴看到您建立这样一个project。 
有一个小建议： 您能不能加一点自我介绍，比如你家的娃目前几岁，目前正在什么阶段，目前正常参考什么样的育儿方式或指导？
这样可能更有参考意义。 谢谢！ 

Philip

**Comment by LennyNiu** [comment]
已添加到新分支july2023，稍后更新完剩余内容再merge
